### ISSUE TITLE
Hyperparameters 

### ISSUE THREAD

**Issue by jaytsien** [EricLee8/Multi-party-Dialogue-MRC#1]
Hi: Can you share hyperparameters such as epoch? Thanks

**Comment by EricLee8** [comment]
Thank you for your interest in our work. The default hyperparameter settings for both datasets are all in file utils/config.py
We are sorry that the two config.py files were omitted on the first submission. We have already submitted them now, you can find them on molweni/utils/config.py and friendsqa/utils/config.py, respectively.
