### ISSUE TITLE
关于数据处理的两个问题

### ISSUE THREAD

**Issue by ahxchzt** [EricLee8/Multi-party-Dialogue-MRC#2]
请问您提供的data中speaker_mask文件是如何得到的呢？里面的index又是什么含义？
请问您为何要在每一个context前面加上pad呢？还望您解惑

**Comment by EricLee8** [comment]
抱歉这么晚才看到，如果我很久没回复可以给我发邮件，repo的issue不常看。
speaker_mask文件是随机mask一个speaker得到的，为了保证可复现性以及比较的公平性，我在实验的时候不是每次训练都随机mask，而是用第一次训练前得到的这个speaker_mask文件来完成全部的实验。index就是utterance的index，因为一个对话里某个speaker可能出现很多次，所以要确定是哪个utterance的speaker才能把它定位出来。
至于context前面加一个pad，这个其实是方便做key-utterance prediction的一个操作。具体地，我们为了方便将key-utterance prediction任务作为一个多分类任务以使用cross-entropy loss进行优化（而不是将其作为二分类使用binary cross entropy，这样会导致negative example太多），定义了一个max utterance（见config.py)，并把分类任务定义为在max utterance个utterance中选取最好的key-utterance（这样方便矩阵操作和调用CrossEntropyLoss）。这样就会出现一个问题，有些对话的utterance数小于max-utterance，这时候我们会定义一个padding utterance来把每个对话的utterance数pad到max utterance，实际上就是加在最前面的那个pad token。你可以在[这个函数](https://github.com/EricLee8/Multi-party-Dialogue-MRC/blob/4e7f3cc841f7c7e337d936690a8986b1583dcd02/molweni/utils/utils.py#L202)里找到，我们在gather utterance信息的时候会把每个utterance的gather id计算出来，那么对于padding utterance，我们就把它的gather id定义为那个pad token的index。在计算CrossEntropy的时候，我们会用utterance_p_mask把这些padding的utterance处的logit变为负无穷，实际它们不影响loss的计算。说起来有点绕，简单的说这个padding就是方便模型训练。
